# Generated by Django 4.1.7 on 2023-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=100)),
                ('grade_class', models.CharField(max_length=150)),
                ('picture', models.ImageField(default='Lionel-Messi-11.jpg', upload_to='user', verbose_name='picture')),
                ('type_user', models.CharField(choices=[('admin', 'admin'), ('student', 'student'), ('teacher', 'teacher'), ('parent', 'parent')], default='student', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
