# Generated by Django 2.2.8 on 2023-02-27 22:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=users.models.path_and_rename, verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student'), ('teacher', 'teacher'), ('parent', 'parent')], default='student', max_length=10),
        ),
    ]
